- .gitignore
Ignore `nb-configuration.xml` for NetBeans IDE users. Normally this file is not created, but in this case the plugin baseline is so old that tests and `hpi:run` cannot run on Java 8, so a specific JDK must be selected. So must specify
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project-shared-configuration>
<properties xmlns="http://www.netbeans.org/ns/maven-properties-data/1">
<netbeans.hint.jdkPlatform>JDK_1.7</netbeans.hint.jdkPlatform>
</properties>
</project-shared-configuration>
```
This is in fact fine to check in (intended to be sharable), but I predict @stephenc would violently disagree.
> Ignore nb-configuration.xml.

- src/main/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl.java
As mentioned in #21, certificate credentials are not working well.
I found and fixed one bug, which was a stack trace when `password == null`. The problem is that `doCheckKeyStoreFile` receives a null `password` even when one is visibly set in the form. The check is actually correct when the page is first loaded, but then called again incorrectly if you even focus either the `keyStoreFile` or `password` fields, overwriting the original form validation with a bogus error. Easily reproduced with `src/test/resources/com/cloudbees/plugins/credentials/impl/test.p12` (password `password`).
I tried updating the baseline to 1.532 where JENKINS-19124 is fixed, and deleting the special `<script>`s in `FileOnMasterKeyStoreSource/config.jelly` and `UploadedKeyStoreSource/config.jelly`. This did not …
> Trying to fix certificate upload & password checking

- src/main/resources/lib/credentials/select.jelly
- I think it only works by accident with script tags
- When the adjunct is initially included the script and css elements are injected at the point where the st:adjunct
tag is first referenced.
- Thus these tags form part of the DOM that can be removed (e.g. when part of a repeatable / hetero list)
- Because the script is executed, removing the DOM node cannot un-execute the script, so script tags are safe
- Removing the css's link tag, however, removes the styling... and the adjunct manager doesn't know.
- What this hack does is inject the CSS at the end of the DOM's head tag (yes triggering a reflow) but only
if the CSS link is not present already. The JavaScript tag (because we are bypassing st:adjunct) is conditionally
appended to the DOM's body so that it can be fetched while other …
> Adjuncts do not include CSS correctly for removable dom fragments

- src/main/java/com/cloudbees/plugins/credentials/domains/URIRequirementBuilder.java
- src/test/java/com/cloudbees/plugins/credentials/domains/DomainTest.java
Fixes a bug I found while investigating jenkinsci/ghprb-plugin/issues/117.
When a path is used in the URIRequirementBuilder, it cleared any SchemeRequirement already set.
This appears to be a copy-paste error.
> Fix a small bug in URIRequirementBuilder.

- src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinition.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinitionTest.java
Not sure whether this is in fact the intended use of `isDefaultValue()`, but the lack of Javadoc meant I had to guess. This PR may well be misguided.
https://issues.jenkins-ci.org/browse/JENKINS-32642
@reviewbybees
> [FIX JENKINS-32642] Consider default value to be the default

- src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinition.java
This pull request swaps the order of 2 parameters in a call to CredentialsParameterDefinition constructor to match the definition. This error caused the Rebuild Plugin to swap the parameter description with the credential GUID when a rebuild was requested. This in turn selected the credential at the top of the dropdown list instead of the credential from the specified build thereby defeating the reason for using the rebuild plugin (see issue [JENKINS-29646](https://issues.jenkins-ci.org/browse/JENKINS-29646?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)))
I have been using this for a couple weeks and it has solved the issue with the Rebuild Plugin behaving in the expected manner.
> [JENKINS-29646] - fix bug in constructor call that breaks rebuild-plugin

- src/main/java/com/cloudbees/plugins/credentials/UserCredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTest.java
- src/test/java/com/cloudbees/plugins/credentials/domains/DomainTest.java
See description of the issue in [JENKINS-33944](https://issues.jenkins-ci.org/browse/JENKINS-33944).
Work included:
@reviewbybees esp. @stephenc
> [JENKINS-33944] User-scoped credentials cannot be looked up

- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/configure.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/newDomain.jelly
See [JENKINS-34329](https://issues.jenkins-ci.org/browse/JENKINS-34329)
This issue is fixed with this PR that addresses the front-end part together with #44 that addresses the backend part [here](https://github.com/jenkinsci/credentials-plugin/pull/44/files#diff-07a1bb67aa87372e137c913c122e6da7L199) and [here](https://github.com/jenkinsci/credentials-plugin/pull/44/files#diff-07a1bb67aa87372e137c913c122e6da7L323)
@reviewbybees esp. @stephenc
> [JENKINS-34329] Stop allowing to update domains to have blank names

- pom.xml
- src/findbugs/excludesFilter.xml
- src/main/java/com/cloudbees/plugins/credentials/CredentialsScope.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStore.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
- src/main/java/com/cloudbees/plugins/credentials/NameWith.java
- src/main/java/com/cloudbees/plugins/credentials/common/AbstractIdCredentialsListBoxModel.java
- src/main/java/com/cloudbees/plugins/credentials/common/IdCredentials.java
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/action.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/FileOnMasterKeyStoreSource/config.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/UploadedKeyStoreSource/Upload/complete.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/UploadedKeyStoreSource/Upload/index.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/UploadedKeyStoreSource/config.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/credentials.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/Messages_ja.properties
- src/main/resources/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl/credentials.jelly
- src/main/resources/index.jelly
Upgrade to new parent pom. More info [here](https://github.com/jenkinsci/plugin-pom)
@reviewbybees
> [JENKINS-33863] Upgrade to plugin parent pom 2.4

- src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
- src/main/resources/lib/credentials/select.jelly
> [FIXED JENKINS-35168] Resolve the context `ModelObject` when `it` isn't a `ModelObeject`

- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStore.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
- src/main/java/com/cloudbees/plugins/credentials/cli/BaseCredentialsCLICommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/CreateCredentialsByXmlCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/CreateCredentialsDomainByXmlCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/CredentialsStoreOptionHandler.java
- src/main/java/com/cloudbees/plugins/credentials/cli/DeleteCredentialsCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/DeleteCredentialsDomainCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/GetCredentialsAsXmlCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/GetCredentialsDomainAsXmlCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/ListCredentialsCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/ListCredentialsContextResolversCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/ListCredentialsProvidersCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/UpdateCredentialsByXmlCommand.java
- src/main/java/com/cloudbees/plugins/credentials/cli/UpdateCredentialsDomainByXmlCommand.java
- src/main/resources/com/cloudbees/plugins/credentials/Messages.properties
- src/main/resources/com/cloudbees/plugins/credentials/cli/Messages.properties
- src/test/java/com/cloudbees/plugins/credentials/CredentialsStoreActionTest.java
- src/test/java/com/cloudbees/plugins/credentials/cli/CLICommandsTest.java
[JENKINS-28407](https://issues.jenkins-ci.org/browse/JENKINS-28407)
> [JENKINS-28407] Create Credentials through CLI

- src/main/java/com/cloudbees/plugins/credentials/ContextInPath.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsDescriptor.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStore.java
- src/main/java/com/cloudbees/plugins/credentials/impl/BaseStandardCredentials.java
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsSelectHelper/WrappedCredentialsStore/credential.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/update.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/newCredentials.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/BaseStandardCredentials/id-and-description.jelly
- src/test/java/com/cloudbees/plugins/credentials/impl/BaseStandardCredentialsTest.java
[JENKINS-36315](https://issues.jenkins-ci.org/browse/JENKINS-36315)
@reviewbybees
> [FIXED JENKINS-36315] Make it easier to infer the context in form binding

- src/test/java/com/cloudbees/plugins/credentials/CredentialsStoreActionTest.java
- src/test/java/com/cloudbees/plugins/credentials/ViewCredentialsActionTest.java
- src/test/java/com/cloudbees/plugins/credentials/XmlMatchers.java
[JENKINS-37801](https://issues.jenkins-ci.org/browse/JENKINS-37801)
This PR relaxes the smoke tests in `ViewCredentialsActionTest` and `CredentialsStoreActionTest` changing from strict string comparison on XML results to XMLUnit's similar comparison ignoring attributes starting with "_"
This way we preserve backwards compatibility and the test is a little (IMHO) more robust to no relevant changes in the XML like adding a `_class` attribute
> [JENKINS-37801] ViewCredentialsActionTest#smokes and CredentialsStoreActionTest are failing against stable-2.7

- src/main/resources/lib/credentials/select/select.js
When a credentials selector is dynamicaly added to the DOM and
no Behaviour was specified yet (for instance, in [JENKINS-37707],
when adding a first Credentials Binding wrapper, and we don't
have an other plugin, like Git, to ensure the credentials JS lib
is already loaded in the page), then some new Behaviours are
specified, and retro-applied to existing DOM elements (with
Behaviour.applySubtree in a timeout function).  It's a hack,
which almost works, but there was an issue with elements with
class 'credentials-select-control': there is a Behaviour specified
for them, but Behaviours are only applied to their children, not
themselves.  That's what this (rather obvious) patch fixes.
It seems to be enough to fix the error reported in [JENKINS-37707].
> [JENKINS-37707] fix missing Behaviour in /lib/credentials:select

- src/main/java/com/cloudbees/plugins/credentials/common/AbstractIdCredentialsListBoxModel.java
Used implicitly by https://github.com/jenkinsci/git-plugin/pull/437 and https://github.com/jenkinsci/subversion-plugin/pull/169.
@reviewbybees
> [JENKINS-38048] Relax nullability on Item/ItemGroup context parameters

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
Amends #58. Noticed from https://github.com/jenkinsci/credentials-binding-plugin/pull/27.
@reviewbybees esp. @stephenc
> [JENKINS-20139] Inaccurate/incomplete Javadoc for `track` overloads

- pom.xml
Prepare the fix for https://issues.jenkins-ci.org/browse/JENKINS-41946
Bump parent pom from jenkins:2.10 to jenkins:2.21
> Bump parent pom from jenkins:2.10 to jenkins:2.21

- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinition.java
Allows use of the credentials parameter type in Declarative.
cc @reviewbybees and @vivek
> [FIXED JENKINS-44588] Add "credentials" symbol to parameter

- src/main/java/com/cloudbees/plugins/credentials/CredentialsDescriptor.java
Parameter was not documented, simpler to document it than worry about the compiler warning.
> Fix CredentialsDescriptor javadoc warning

- src/main/resources/lib/credentials/select.jelly
This PR fixes the misplaced down arrow on the credentials 'Add' button  [JENKINS-52936] .
The 'hetero-list-add' css class is basically added to the button  which provides the necessary 25px padding-right to push the arrow to the right.
> [JENKINS-52936] Fixes Add button overlap with down arrow

- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/SecretBytes.java
- src/main/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl.java
Using `{@link byte[]}` on JDK11 crashes, cf. https://bugs.openjdk.java.net/browse/JDK-8200432
So we change this construct to move forward. (To unblock https://github.com/jenkinsci/credentials-plugin/pull/119)
> Fix Javadoc Error using @link byte[]

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/index.properties
There's a distinction between `use` and `usage` -- `use` covers way more categories than `usage`, so on average `use` is the right word.
> grammar: use; punctuation

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsParameterDefinition/help.html
This information is used multiple times, automatically in the jenkins.io doc.
@daniel-beck
> Avoid confusion between UUID and ID

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTest.java
See [JENKINS-49235](https://issues.jenkins-ci.org/browse/JENKINS-49235). Subsumes #97.
This change removes fingerprints for nodes which do not currently exist in Jenkins. Notably, this makes credentials tracking for ephemeral, cloud-provisioned agents completely useless, so as requested in #97 I've created [JENKINS-51694](https://issues.jenkins-ci.org/browse/JENKINS-51694) as a tracking issue for adding that functionality back in and referenced it in a `TODO` comment in the code.
@reviewbybees 
CC @fraz3alpha
> [JENKINS-49235] Prune fingerprints of nonexistent node credentials (and add ticket to fix tracking for ephemeral nodes)

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/index.jelly
Currently the credential ID is shown in the global credentials screen (`/credentials`), but not in the domain-scoped credentials screen (`/credentials/store/system/domain/_/`), which makes it a little harder for users to work with domain-scoped credentials.
This PR adds the credential ID to the domain-scoped credentials screen, so that users no longer need to look at the path in their address bar to work out the credential ID they should paste into their Jenkinsfiles.
> Show credential ID in DomainWrapper view

- src/main/java/com/cloudbees/plugins/credentials/SecretBytes.java
Partially fixes https://github.com/jenkinsci/configuration-as-code-plugin/issues/1170
The other part is a null check in JCasC
Before this change, if one credential was a FileCredentialsImpl then no credentials could be exported (see the linked issue above), after this change and a null check in JCasC I can export all credentials including FileCredentialsImpl
> Return object in converter if is SecretBytes

- README.md
Also remove reference to wiki documentation.  Wiki link immediately redirects to plugins.jenkins.io which is this file.
> Use working link to CHANGELOG

- README.md
The README strongly words that GitHub issues will be ignored and closed. However, GitHub issues are disabled on this repository, so creating them is impossible. This makes this description obsolete.
Removing the image will also drop the dependency on an external hoster and image, and remove a silly meme image increasing perceived professionality.
Removing the strongly worded ticket ignoring notice improves perceived welcome-ness, decreasing perceived rejection/opposition.
> Drop mention of disabled GitHub issues

- src/main/java/com/cloudbees/plugins/credentials/GlobalCredentialsConfiguration.java
- src/test/java/com/cloudbees/plugins/credentials/casc/CredentialsCategoryTest.java
- src/test/resources/com/cloudbees/plugins/credentials/casc/credentials-category.yaml
See [JENKINS-61880](https://issues.jenkins-ci.org/browse/JENKINS-61880)
Add a `@Symbol` to the category so it's rendered properly in JCasC YAML.
> [JENKINS-61880] GlobalCredentialsConfiguration JCasC compatibility

- src/main/resources/lib/credentials/select.jelly
- src/main/resources/lib/credentials/select/select.js
Preparing for change in core to the icon, ref: https://github.com/jenkinsci/jenkins/pull/4663
Testing:
* Create a pipeline, 
* Tick this build is parameterised
* Add a credential parameter
* Save
* Click build with parameters
You should see no change before or after this change
cc @jvz
> Use standard jelly help tag

- src/main/java/com/cloudbees/plugins/credentials/SecretBytes.java
https://github.com/jenkinsci/jenkins/pull/4636#issuecomment-640883683, detected in https://github.com/jenkinsci/bom/pull/240
Otherwise against 2.231+ you get
```
java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value. Expected the discarded bits to be zero.
at org.apache.commons.codec.binary.Base64.validateCharacter(Base64.java:803)
at org.apache.commons.codec.binary.Base64.decode(Base64.java:477)
at org.apache.commons.codec.binary.BaseNCodec.decode(BaseNCodec.java:482)
at org.apache.commons.codec.binary.BaseNCodec.decode(BaseNCodec.java:465)
at org.apache.commons.codec.binary.Base64.decodeBase64(Base64.java:699)
at com.cloudbees.plugins.credentials.SecretBytes.isSecretBytes(SecretBytes.java:302)
at …
```
> Fix SecretBytesTest.isSecretBytes for 2.235.x PCT

- src/main/java/com/cloudbees/plugins/credentials/ViewCredentialsAction.java
Fix regression from #150, amends #154 
/cc @timja
> Credentials action should be hidden only for the root Jenkins, not for folders or users

- src/main/resources/com/cloudbees/plugins/credentials/Messages_fr.properties
The word `esclaves` appeared in the French documentation for the credentials plug-in. I changed it to `agents` (consistent with previous PR).
> Replace esclave with agent in credentials plug-in (fr)

- docs/user.adoc
This was probably caused by a copy & paste error.
> Fix 'Retrieving credentials' section

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTest.java
This moves the sorting logic from `CredentialsProvider#lookupCredentials` to `CredentialsProvider#getCredentialIds`, so that it happens after applying matchers, and only when being pulled in a UI.
> [JENKINS-65333] Sort credentials entries only for UI

- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl.java
- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/UploadedKeyStoreSource/Upload/complete.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/UploadedKeyStoreSource/Upload/index.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/UploadedKeyStoreSource/config.jelly
- src/test/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImplTest.java
- src/test/resources/com/cloudbees/plugins/credentials/impl/invalid.p12
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
Jira tickets: [JENKINS-63761](https://issues.jenkins.io/browse/JENKINS-63761) and [JENKINS-64542](https://issues.jenkins.io/browse/JENKINS-64542) (at least)
⁉️ There are multiple things corrected here. The main one is the bug introduced since 2.254 in https://github.com/jenkinsci/jenkins/pull/4910. Due to the COOP header, the new window approach to upload certificate is no longer working. The second problem was about the warning/error message when you are uploading the certificate.
The second part about the validation was filed as a bug in the tracker: [JENKINS-65616](https://issues.jenkins.io/browse/JENKINS-65616).
✔️ Both are resolved by putting the file input field "inline" inside the form instead of using a …
> [JENKINS-62761] Certificate upload correction

- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/CredentialsNameProvider.java
- src/main/java/com/cloudbees/plugins/credentials/common/StandardCredentials.java
- src/main/java/com/cloudbees/plugins/credentials/common/StandardUsernameCredentials.java
- src/main/java/com/cloudbees/plugins/credentials/common/StandardUsernamePasswordCredentials.java
- src/main/java/com/cloudbees/plugins/credentials/common/UsernameCredentials.java
- src/main/java/com/cloudbees/plugins/credentials/common/UsernamePasswordCredentials.java
- src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl.java
- src/main/resources/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl/credentials.jelly
- src/main/resources/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl/help-usernameSecret.html
- src/test/java/com/cloudbees/plugins/credentials/CredentialsStoreActionTest.java
- src/test/java/com/cloudbees/plugins/credentials/impl/DummyIdCredentials.java
- src/test/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImplTest.java
[JENKINS-44860](https://issues.jenkins.io/browse/JENKINS-44860)
https://github.com/jenkinsci/credentials-binding-plugin/pull/131#issuecomment-832854838
> [JENKINS-44860] `UsernameCredentials.isUsernameSecret`

- src/main/resources/com/cloudbees/plugins/credentials/impl/BaseStandardCredentials/id-and-description.jelly
- src/test/java/com/cloudbees/plugins/credentials/impl/BaseStandardCredentialsTest.java
See details in [JENKINS-66514](https://issues.jenkins.io/browse/JENKINS-66514)
The fix is to remove the unnecessary explicit `checkUrl` so the legacy
validation method isn't used. The check URL will be calculated
automatically and the "new" (years old) mechanism kicks in.
The test is checking that the validation error shows up when needed (and
only when needed), so this change does not cause a regression.
> [JENKINS-66514] BaseStandardCredentials ID validation error

- src/main/webapp/images/userpass.svg
@Wadeck That addresses your concerns outlined from https://github.com/jenkinsci/credentials-plugin/pull/230#pullrequestreview-768696157
I previously didn't notice the password asterisks being out of their box. This PR will address that.
Before: 
After:
> fix: Address post merge comment (Improvement of userpass.svg)

- src/main/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl.java
- src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl.java
- src/test/java/com/cloudbees/plugins/credentials/casc/CredentialsCategoryTest.java
- src/test/java/com/cloudbees/plugins/credentials/casc/SystemCredentialsTest.java
https://issues.jenkins.io/browse/JENKINS-66639
For this specific feature, I have run test before and after adding the Symbol: both run are fine.
> [JENKINS-66639] adding explict jcasc symbol on CertificateCredentialImpl and UsernamePasswordCredentialsImpl classes

- pom.xml
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/sidepanel.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/index.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/sidepanel.jelly
- src/main/webapp/images/credential.svg
- src/main/webapp/images/credentials.svg
- src/main/webapp/images/folder-store.svg
- src/main/webapp/images/move.svg
- src/main/webapp/images/new-credential.svg
- src/main/webapp/images/new-domain.svg
- src/main/webapp/images/system-store.svg
- src/main/webapp/images/user-store.svg
SVG icons from core (added in https://github.com/jenkinsci/credentials-plugin/pull/230 ) can be referenced by class instead of depending on file location in core. That should be more future-proof and seems to be the preferred way.
- [n/a] Link to relevant issues in GitHub or Jira
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> Refer to icons using classes instead of filenames

- src/main/java/com/cloudbees/plugins/credentials/Credentials.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
https://github.com/jenkinsci/github-branch-source-plugin/pull/527 is a demonstrated use case, and https://github.com/jenkinsci/conjur-credentials-plugin/issues/21 a proposed one.
This new SPI requires use of the `CredentialsProvider.findCredentialById` method, which passes a (mandatory) `Run` argument and is the normal way to look up a particular credential during a build. (`credentials-binding` has long used it—https://github.com/jenkinsci/credentials-binding-plugin/pull/169 is the integration test—and the revised version of https://github.com/jenkinsci/git-plugin/pull/1242 is able to use it consistently as well.) There are other lookup methods which take an `Item` (~ `Job`) or even `ItemGroup` (~ `Jenkins` / `Folder` / `MultiBranchProject` / `OrganizationFolder`) context, which would …
> Introduce `Credentials.forRun` to contextualize secrets

- src/main/resources/lib/credentials/select.jelly
See [JENKINS-68163](https://issues.jenkins.io/browse/JENKINS-68163)
The button is now sized properly:
This occurs in a parameterized build with credentials input. Other occasions are unaffected.
> Fix button size of "+ Add"

- src/main/resources/lib/credentials/select.jelly
Regression in [1105 release](https://github.com/jenkinsci/credentials-plugin/releases/tag/1105.vb_4e24a_c78b_81).  The `div` that was added to surround the `select` seems to prevent calls to the `attrs.checkMethod`.
When using a GitHub branch source, an empty credentials field no longer displays the warning that a credential is recommended.  Other uses of credentials seem to have the same behavior.  Validation checks are no longer called.
When the `div` is included in the page, the credential validation callback is not invoked. When the `div` is removed from the page, the credential validation callback is invoked.
It is unclear to me why the addition of a `div` would change the validation behavior.
Review the differences with [white space …
> [JENKINS-68616] Enable field validation checks

- docs/implementation.adoc
`queues` is not the right word (and is a typo), I assume `cues` was meant, but I think hint is probably clearer.
> Reword sentence

- src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsSnapshotTaker.java
This adds a snapshot taker for StandardUsernamePasswordCredentials.  This is needed to fix an issue in hashicorp-vault plugin which currently prevents ssh keys being sent to agents which is being developed in https://github.com/jenkinsci/hashicorp-vault-plugin/pull/218
> Add snapshot taker for special `StandardUsernamePasswordCredentials` impls

- src/main/java/com/cloudbees/plugins/credentials/PluginImpl.java
Post cleanup to https://github.com/jenkinsci/credentials-plugin/pull/321.
The icon lives on in the folders plugin and shouldn't be registered under the credentials namespace any longer.
> Remove folder-store from array

- pom.xml
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsSelectHelper/WrappedCredentialsStore/credential_it.properties
- src/main/resources/com/cloudbees/plugins/credentials/common/Messages_it.properties
The same as #355 but also fix test failures.
It is important to update to 4.46 to remove test flakiness in:
com.cloudbees.plugins.credentials.CredentialsParameterDefinitionTest.onlyIncludeUserCredentialsWhenChecked
> Bump plugin from 4.40 to 4.46 and accompanying changes

- src/main/resources/lib/credentials/select/select.js
I haven't managed to track down why this happens but I get a type error when loading configure job screens (at least freestyle).
The changed function gets called 3 times for me and the third one is not a dom element, it's an array containing two functions.
this is a work around but shouldn't cause any harm
(this isn't the error from https://github.com/jenkinsci/bom/pull/1133 but it's the first error I saw loading the page)
> Prevent type error from loading non element

- .github/workflows/cd.yaml
Current release is failing because it's trying to use Java 8.
This version uses 11:
https://github.com/jenkins-infra/github-reusable-workflows/blob/afd648babebffa5ccba9e3d4fd7810e7e6be583a/.github/workflows/maven-cd.yml#L60
See template:
https://github.com/jenkinsci/.github/blob/master/workflow-templates/cd.yaml
> Update CD template to recommended version (fixes release)

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsSelectHelper/WrappedCredentialsStore/dialog.jelly
- src/main/resources/lib/credentials/dialog.js
- src/main/resources/lib/credentials/select.jelly
Hello,
Hacktoberfesting to solve [JENKINS-69653](https://issues.jenkins.io/browse/JENKINS-69653).
Manually test to ensure 'Cancel' and 'Add' buttons works as before:
https://user-images.githubusercontent.com/47667812/196411047-fda17d60-dcd1-44a1-8dc6-c9e02a001bfe.mov
> [JENKINS-69653] Un-inlining dialog.jelly

- src/main/java/com/cloudbees/plugins/credentials/SystemCredentialsProvider.java
See [JENKINS-68791](https://issues.jenkins.io/browse/JENKINS-68791).
> [JENKINS-68791] Missing icon for global credential store

- src/main/resources/lib/credentials/select.jelly
- src/main/resources/lib/credentials/select/select.css
https://issues.jenkins.io/browse/JENKINS-69379
I have set this to be a draft pull request as I wanted to discuss if this is the correct approach for this fix.
When investigating the black line on the add button issue, I noticed that the other 'Add' buttons on the page didn't include 'jenkins-button' on them. 
Example of a non-problematic add button on the same page:
I removed the 'jenkins-button' bits from the jelly file and tested, and now all of the buttons are looking consistent. Manual testing done with problem button:
Do you think this is the right approach? Is there something I am missing about removing the 'jenkins-button' bits from the button?
> [JENKINS-69379] Removed 'jenkins-button jenkins-button--tertiary' from select.jelly

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/configure.jelly
Forgotten in #443. Tested by running `docker-commons` tests against this plugin, which failed before this PR and passed after this PR.
> Remove more usages of Prototype

- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
- src/main/java/com/cloudbees/plugins/credentials/cli/BaseCredentialsCLICommand.java
In https://github.com/jenkinsci/jenkins/pull/7778 we switched core from KXML2 to StAX. This plugin seems to still be using an XPP3-based parser, though, which is inconsistent with core and probably suffers from the same emoji parsing bug (though in the context of a credentials file it probably doesn't matter). In any case, it is simpler and more consistent to use the same `StandardStaxDriver` used by core. To implement that we just use `XStream2#getDefaultDriver` to delegate driver selection to core.
In addition to running `mvn clean verify` I also ran `mvn clean verify` against a work-in-progress version of Jenkins core with XPP3 completely removed, which had previously been failing before this PR but started passing after this PR.
```[tasklist]
```
> Switch from XML Pull Parser v3 to Streaming API for XML (StAX) on newer cores

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsParameterDefinition/config.jelly
- src/test/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinitionTest.java
Add missing markup formater for CredentialParameterDefinition to fix [[JENKINS-52386] - credentials() parameter does not support HTML in description](https://issues.jenkins.io/browse/JENKINS-52386)
> [JENKINS-52386] Add preview for markup of a CredentialParameterDefinition

- src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
I am prototyping a custom credentials type that has nested `Describable` fields with `Descriptor.newInstance` overrides, and this PR is necessary for data binding to work correctly for those credentials.
`Descriptor.bindJSON` is a drop-in replacement for `StaplerRequest.bindJSON` from https://github.com/jenkinsci/jenkins/pull/5417 and the only difference should be that the former correctly calls `Descriptor.newInstance` while the latter does not.
Marking this as `developer` rather than `bug` because it never worked previously, so there should not be any existing credential types where the difference would matter in a way that affects users as a `bug`.
```[tasklist]
```
> Use `Descriptor.bindJSON` to support complex describable fields in custom credentials

- src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
- src/main/resources/lib/credentials/select/select.js
- src/test/java/com/cloudbees/plugins/credentials/CredentialsSelectHelperTest.java
- src/test/resources/com/cloudbees/plugins/credentials/CredentialsSelectHelperTest/CredentialsSelectionAction/index.jelly
Motivated by https://github.com/jenkinsci/jenkins/pull/8351.
That PR changes `FormApply#applyResponse` method to make it CSP compatible in a way that does not allow to execute arbitrary javascript as a callback.
Looking at the usages of `FormApply#applyResponse` in the ecosystem its most common (and perhaps intended) use is to show a notification after "Apply" button (or alike) was clicked. In credentials-plugin it's used in a "add credentials in-place" form, and the calls are rather uncommon.
Two calls are `FormApply.applyResponse("window.alert(...)")`, which could easily be replaced by the new CSP compatible version `FormApply.showNotification` from the core PR linked above.
Third call is worse - `FormApply.applyResponse("window.credentials.refreshAll();")`.
My initial attempt was to …
> Do not use `FormApply#applyResponse` to execute arbitrary javascript

- docs/consumer.adoc
- docs/implementation.adoc
- src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinition.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterValue.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStore.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
- src/main/java/com/cloudbees/plugins/credentials/SystemCredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/UserCredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/ViewCredentialsAction.java
- src/main/java/com/cloudbees/plugins/credentials/common/AbstractIdCredentialsListBoxModel.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTest.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsUnavailableExceptionTest.java
- src/test/java/com/cloudbees/plugins/credentials/MockFolderCredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/casc/CredentialsProviderTest.java
- src/test/java/com/cloudbees/plugins/credentials/casc/SystemCredentialsTest.java
- src/test/java/com/cloudbees/plugins/credentials/domains/DomainRestrictedCredentialsTest.java
- src/test/java/com/cloudbees/plugins/credentials/domains/DomainTest.java
- src/test/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImplTest.java
This is the implementation of
https://github.com/jenkinsci/jenkins/pull/4848 for Credentials API.
cf. https://github.com/jenkinsci/jep/blob/31859bedd4594df528428ccc737117b44b786fce/jep/227/README.adoc
This will allow consumers of the credentials API to remove references to deprecated acegi APIs.
Some overloads methods were renamed in order to avoid the ambiguous signatures involving `Item` and `ItemGroup`.
For example, `lookupCredentials` become `lookupCredentialsInItem` and `lookupCredentialsInItemGroup`.
cc @jglick 
```[tasklist]
```
> [JEP-227][JENKINS-39324] Replace Acegi Security with Spring Security APIs

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStore.java
_May_ fix https://github.com/jenkinsci/credentials-plugin/pull/490#issuecomment-1782975527 though cause is unclear so improving the error message as well.
> Compatibility error in `CredentialsProvider`

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
Follows up #490 
Prefer calling deprecated overrides of `getCredentials(..., Item, ...)` if implemented rather than resolving closest `ItemGroup`.
```[tasklist]
```
> Fix a compatibility error in `CredentialsProvider`

- src/main/resources/lib/credentials/dialog.js
One change from https://github.com/jenkinsci/credentials-plugin/pull/491 was applied to a reference that was not using Prototype.js.
Confirmed interactively that I can see the problem before the change and that with this change the problem is resolved.
No test automation created due to the high effort to create the test and low long term value of the test.
I'd prefer to have a review from @rsandell , @raul-arabaolaza, @yaroslavafenkin, or @ampuscas
> [JENKINS-72364] Close provider dialog window when cancel is clicked

- src/main/java/com/cloudbees/plugins/credentials/SystemCredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/UserCredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTest.java
- src/test/java/com/cloudbees/plugins/credentials/MockFolderCredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/domains/DomainTest.java
- src/test/java/com/cloudbees/plugins/credentials/impl/DummyCredentials.java
https://issues.jenkins.io/browse/JENKINS-72611
Tested interactively, made sure that two credentials cannot have the same ID.
```[tasklist]
```
> [JENKINS-72611] Forbid editing credentials ID

- src/main/java/com/cloudbees/plugins/credentials/SystemCredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/UserCredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTest.java
- src/test/java/com/cloudbees/plugins/credentials/MockFolderCredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/domains/DomainTest.java
- src/test/java/com/cloudbees/plugins/credentials/impl/DummyCredentials.java
Another attempt at https://issues.jenkins.io/browse/JENKINS-72611 as https://github.com/jenkinsci/credentials-plugin/pull/502 caused regressions.
Tested interactively, made sure that two credentials cannot have the same ID. Tested interactively with credentials that are not `IdCredentials` (used [this](https://github.com/jenkinsci/loadfocus-jmeter-load-testing-integration-plugin/blob/d2d2af5b0af276932dfb6c8191d3bb13791d6bc7/src/main/java/com/loadfocus/jenkins/impl/LoadCredentialImpl.java)).
```[tasklist]
```
> [JENKINS-72611] Forbid updating credentials ID for `IdCredentials`

- .github/workflows/jenkins-security-scan.yml
- README.md
I noticed that the LGTM badge in the `README.md` was broken since it [got deprecated](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) quite some time ago. I think the proper replacement would be the Jenkins Security Scan as it includes the LGTM successor CodeQL.
> Enable Jenkins Security Scan

- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl.java
- src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsSnapshotTaker.java
- src/main/resources/com/cloudbees/plugins/credentials/impl/Messages.properties
- src/test/java/com/cloudbees/plugins/credentials/builds/CredentialsParameterBinderTest.java
- src/test/java/com/cloudbees/plugins/credentials/cli/CLICommandsTest.java
- src/test/java/com/cloudbees/plugins/credentials/impl/BaseStandardCredentialsTest.java
- src/test/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImplFIPSTest.java
- src/test/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImplTest.java
Signed-off-by: Olivier Lamy <olamy@apache.org>
> In FIPS environment password must be at least 14 characters

- src/main/java/com/cloudbees/plugins/credentials/SecretBytesRedactionExtension.java
Only affects the log message shown to users of Jenkins 2.463...2.478, so feel free to decline.
none
> Fix typo in name of internal class registering `SecretBytesRedaction`

- src/main/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl.java
- src/main/resources/com/cloudbees/plugins/credentials/impl/Messages.properties
- src/test/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImplTest.java
Uploaded a cert generated inside Azure Key Vault
Tested with https://github.com/jenkinsci/azure-credentials-plugin/pull/274
and checked end 2 end and I can provision VMs with https://plugins.jenkins.io/azure-vm-agents using certificate auth
> Handle password with empty string for certificate auth

- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/cli/CredentialsStoreOptionHandler.java
See https://github.com/jenkinsci/jenkins/pull/9980.
CI build; loaded the plugin in a real Jenkins install and verified that the handler was still loaded by stepping through the code in a debugger
> Register `OptionHandler` through `META-INF/services/annotations` and Annotation Indexer rather than `META-INF/services` and Commons Discovery

- src/main/resources/lib/credentials/select.jelly
https://github.com/jenkinsci/jenkins/pull/10245 changes dropdowns slightly, rather than being appended directly to the `<body>` element, they are now appended within the button's parent element. This has broken the credentials plugin as the dropdown menu's buttons lack a `type`. `type` defaults to `submit` causing the form to submit, whereas we just want to treat it as a plain button.
* Menu works as expected
> Add 'type' to dropdown button
