jenkinsci/credentials-plugin

- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/CredentialsDescriptor.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
- src/main/java/com/cloudbees/plugins/credentials/PluginImpl.java
- src/main/java/com/cloudbees/plugins/credentials/SystemCredentialsProvider.java
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsSelectHelper/dialog.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/index.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/index.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/index.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/newDomain.jelly
- src/main/resources/com/cloudbees/plugins/credentials/SystemCredentialsProvider/index.jelly
- src/main/resources/lib/credentials/select.jelly
- src/test/java/com/cloudbees/plugins/credentials/SystemCredentialsProviderTest.java
Merged in icon-tag-shim-test and then extended it to include icon class name in the descriptor.
I read over the contributing guidelines. I can't see anything not setup right.
> Add icon name to descriptor

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
Implemented comparator to sort credentials by credential name in select lists. For simplicity and safety I only modified the returned ArrayList and not any of the add credential functions or the main display page.
> [JENKINS-31863] Sort Credential select list by credenial name

- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
@reviewbybees see [JENKINS-35130](https://issues.jenkins-ci.org/browse/JENKINS-35130)
> [FIXED JENKINS-35130] Delete and Move credentials do not work with providers that do not have modifiable domains

- src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
- src/main/resources/lib/credentials/select.jelly
See [JENKINS-35150](https://issues.jenkins-ci.org/browse/JENKINS-35150)
@reviewbybees
> [JENKINS-35150] We can be more forgiving of users with misconfigured HTTPS front-ends

- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
- src/main/java/com/cloudbees/plugins/credentials/ViewCredentialsAction.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsStoreActionTest.java
- src/test/java/com/cloudbees/plugins/credentials/ViewCredentialsActionTest.java
> [FIXED JENKINS-24631] Expose the credentials details by the XML/JSON API

- pom.xml
- src/findbugs/excludesFilter.xml
- src/main/antlr4/com/cloudbees/plugins/credentials/matchers/CQL.g4
- src/main/java/com/cloudbees/plugins/credentials/CredentialsMatcher.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsMatchers.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/AllOfMatcher.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/AnyOfMatcher.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/BeanPropertyMatcher.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/CQLSyntaxException.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/ConstantMatcher.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/IdMatcher.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/InstanceOfMatcher.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/NotMatcher.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/ScopeMatcher.java
- src/main/java/com/cloudbees/plugins/credentials/matchers/UsernameMatcher.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsMatchersTest.java
See [JENKINS-35306](https://issues.jenkins-ci.org/browse/JENKINS-35306)
@reviewbybees
> [JENKINS-35306] Credentials Providers need to be able to list credentials without retrieving the backing secret

- src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinition.java
- src/main/java/com/cloudbees/plugins/credentials/common/AbstractIdCredentialsListBoxModel.java
- src/main/resources/com/cloudbees/plugins/credentials/common/Messages.properties
[JENKINS-35306](https://issues.jenkins-ci.org/browse/JENKINS-35306)
@reviewbybees
> [JENKINS-35306] Follow-up to make it easier to use the new listCredentials API for list construction

- src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterValue.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
- src/main/java/com/cloudbees/plugins/credentials/fingerprints/AbstractCredentialsFingerprintFacet.java
- src/main/java/com/cloudbees/plugins/credentials/fingerprints/ItemCredentialsFingerprintFacet.java
- src/main/java/com/cloudbees/plugins/credentials/fingerprints/NodeCredentialsFingerprintFacet.java
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/index.jelly
- src/main/resources/com/cloudbees/plugins/credentials/fingerprints/ItemCredentialsFingerprintFacet/main.jelly
- src/main/resources/com/cloudbees/plugins/credentials/fingerprints/Messages.properties
- src/main/resources/com/cloudbees/plugins/credentials/fingerprints/NodeCredentialsFingerprintFacet/main.jelly
- src/test/java/com/cloudbees/plugins/credentials/fingerpints/FingerprintTest.java
[JENKINS-20139](https://issues.jenkins-ci.org/browse/JENKINS-20139)
- Needs to wait for https://github.com/jenkinsci/credentials-plugin/pull/57 to be merged before we can call this done (see TODO task in code)
> [JENKINS-20139] Add support to track where a credential is used

- src/main/resources/lib/credentials/select/select.js
> [FIXED JENKINS-36034] Workaround for JENKINS-26578 broke htmlunit tests in ssh-credentials

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProviderManager.java
> [FIXED JENKINS-36090] If you add a type restriction, you cannot remove all type restrictions

- src/main/java/com/cloudbees/plugins/credentials/CredentialsUnavailableException.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsUnavailableExceptionTest.java
- A runtime exception to be thrown from Credential getter methods.
- Includes tests of expected throw points to verify that this RuntimeException does not break Jenkins
[JENKINS-36431](https://issues.jenkins-ci.org/browse/JENKINS-36431)
@reviewbybees
> [FIXED JENKINS-36431] Adds CredentialsUnavailableException

- src/main/java/com/cloudbees/plugins/credentials/CredentialsConfidentialKey.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
- src/main/java/com/cloudbees/plugins/credentials/SecretBytes.java
- src/main/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl.java
- src/test/java/com/cloudbees/plugins/credentials/SecretBytesTest.java
- src/test/java/jenkins/security/ConfidentialStoreRule.java
[JENKINS-36432](https://issues.jenkins-ci.org/browse/JENKINS-36432)
@reviewbybees esp @jglick
> [FIXED JENKINS-36432] Added a SecretBytes class to act as a byte[] holder

- README.md
One does not simply incorrectly use this meme.
@reviewbybees 
@stephenc
> Fix up incorrect meme usage

- src/main/resources/lib/credentials/select/select.js
See [JENKINS-38961](https://issues.jenkins-ci.org/browse/JENKINS-38961)
@reviewbybees
> [FIXED JENKINS-38961] Add an escape handler to hide the dialog

- src/test/java/com/cloudbees/plugins/credentials/CredentialsUnavailableExceptionTest.java
[JENKINS-39516](https://issues.jenkins-ci.org/browse/JENKINS-39516)
@reviewbybees specially @stephenc
> [JENKINS-39516] Test failing against jenkins core > 1.626

- src/main/java/com/cloudbees/plugins/credentials/SecretBytes.java
> [JENKINS-39381] add API method which allows to check if a given string is of type ByteSecrets

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsStore.java
- src/main/java/com/cloudbees/plugins/credentials/SystemCredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/UserCredentialsProvider.java
- This method will only be available via Groovy scripting
See [JENKINS-39317](https://issues.jenkins-ci.org/browse/JENKINS-39317)
@reviewbybees
> [FIXED JENKINS-39317] Provide a mechanism for forcing a save of all credential store

- src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
- src/main/resources/lib/credentials/select.jelly
- src/main/resources/lib/credentials/select/select.js
- Also disabled stores should be disabled in the menu
See [JENKINS-41478](https://issues.jenkins-ci.org/browse/JENKINS-41478)
@reviewbybees
> [FIXED JENKINS-41478] Add button should be enabled if any stores are enabled

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/index.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/index.properties
See [JENKINS-40701](https://issues.jenkins-ci.org/browse/JENKINS-40701)
@reviewbybees
> [FIXED JENKINS-40701] Added a disclaimer on imperfection of usage tracking

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
See [JENKINS-41004](https://issues.jenkins-ci.org/browse/JENKINS-41004)
@reviewbybees
> [JENKINS-41004] When duplicate credentials have the same ID, the first one wins

- src/main/resources/lib/credentials/select/select.css
See [JENKINS-41512](https://issues.jenkins-ci.org/browse/JENKINS-41512)
@reviewbybees
> [JENKINS-41512] Use @media query to scale select max-width

- src/main/resources/lib/credentials/select/select.css
> Fix Add button drop down indicator

- src/main/resources/lib/credentials/select.jelly
Needed from some plugins.
@reviewbybees
> Allow <c:select checkMethod="post"/>

- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/ContextMenuIconUtils.java
> Updated parent POM

- src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
> Removing unused import

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsSelectHelper/WrappedCredentialsStore/credential.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/update.jelly
- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/newCredentials.jelly
- src/main/resources/com/cloudbees/plugins/credentials/ViewCredentialsAction/index.jelly
Per https://github.com/jenkinsci/credentials-plugin/pull/62#discussion_r254006084
> replace j:local with j:scope

- src/main/java/com/cloudbees/plugins/credentials/ViewCredentialsAction.java
- src/main/resources/com/cloudbees/plugins/credentials/ViewCredentialsAction/action.jelly
[JENKINS-56607](https://issues.jenkins-ci.org/browse/JENKINS-56607)
> [JENKINS-56607] Fix permission check in sidepanel

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
Pre-merging some changes from #119 that were unrelated.
> Add incrementals support

- src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterValue.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/SystemCredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/ViewCredentialsAction.java
- src/test/java/com/cloudbees/plugins/credentials/MockFolderCredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/SystemCredentialsProviderTest.java
- src/test/java/com/cloudbees/plugins/credentials/cli/CLICommandsTest.java
- src/test/java/com/cloudbees/plugins/credentials/fingerpints/FingerprintTest.java
- Use `ACL.as`
- Remove unused imports
- Removed some unused local vars
- Let Java figure out the type itself
> Do some minor cleanups

- pom.xml
Switch from the wiki to GitHub
> Use GitHub docs for plugins.jenkins.io

- pom.xml
for improved glorious export and improved security!
> bump configuration-as-code-plugin to v1.34

- src/main/java/com/cloudbees/plugins/credentials/GlobalCredentialsConfiguration.java
Downstream from https://github.com/jenkinsci/jenkins/pull/4546
> Add support for future Manage Jenkins layout

- src/main/java/com/cloudbees/plugins/credentials/casc/CredentialsRootConfigurator.java
- src/test/java/com/cloudbees/plugins/credentials/casc/CredentialsProviderTest.java
- src/test/resources/com/cloudbees/plugins/credentials/casc/CredentialsProviderExtension.yaml
See [JENKINS-61900](https://issues.jenkins-ci.org/browse/JENKINS-61900).
/cc @jenkinsci/configuration-as-code-plugin-developers
> [JENKINS-61900] JCasC support for CredentialsProvider extensions

- README.md
- src/main/java/com/cloudbees/plugins/credentials/util/XMLUtils.java
And suppress a warning it found.
> Add lgtm badge

- src/main/java/com/cloudbees/plugins/credentials/GlobalCredentialsConfiguration.java
- src/main/resources/com/cloudbees/plugins/credentials/GlobalCredentialsConfiguration/index.jelly
> Fix runtime error from type erasure

- src/main/java/com/cloudbees/plugins/credentials/SecretBytes.java
- src/test/java/com/cloudbees/plugins/credentials/SecretBytesTest.java
Fixes https://github.com/jenkinsci/configuration-as-code-plugin/issues/1425. Follows up #152.
> Another IllegalArgumentException from SecretBytes in 2.235.x, this time fromString

- src/main/resources/com/cloudbees/plugins/credentials/ViewCredentialsAction/index.jelly
- src/main/resources/com/cloudbees/plugins/credentials/ViewCredentialsAction/index.properties
This PR localizes the `Stores scoped to` string.
> Localize the "Stores scoped to" string

- src/main/java/com/cloudbees/plugins/credentials/UserCredentialsProvider.java
Not sure what 5ad742bac2d503c1b0537799985a50af1f5b1885 was about, but this is simpler and uses currently recommended APIs better.
> Simplified use of User.get and ACL.as

- docs/README.adoc
- docs/faq.adoc
- docs/fflags.adoc
- pom.xml
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
This PR has a few items:
* Updated parent pom
* SafeVarargs annotations on some things
* Added documentation page about feature flags (system properties)
* Started an FAQ with some higher level concerns based on frequent user confusion (and a little bit of inspiration from recent research done regarding external secrets managers)
> Add more documentation along with minor maintenance

- docs/user.adoc
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProviderFilter.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProviderTypeRestriction.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsScope.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsTypeFilter.java
- src/main/java/com/cloudbees/plugins/credentials/common/AbstractIdCredentialsListBoxModel.java
- src/main/java/com/cloudbees/plugins/credentials/domains/PathSpecification.java
- src/main/java/com/cloudbees/plugins/credentials/domains/SchemeSpecification.java
- src/main/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl.java
- src/main/resources/com/cloudbees/plugins/credentials/BaseCredentials/help-scope.html
- src/main/resources/com/cloudbees/plugins/credentials/domains/HostnamePortSpecification/help-excludes.html
- src/main/resources/com/cloudbees/plugins/credentials/domains/HostnamePortSpecification/help-includes.html
- src/main/resources/com/cloudbees/plugins/credentials/domains/HostnameSpecification/help-excludes.html
- src/main/resources/com/cloudbees/plugins/credentials/domains/HostnameSpecification/help-includes.html
- src/main/resources/com/cloudbees/plugins/credentials/domains/PathSpecification/help-excludes.html
- src/main/resources/com/cloudbees/plugins/credentials/domains/PathSpecification/help-includes.html
- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/FileOnMasterKeyStoreSource/help-keyStoreFile.html
- src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTest.java
Removing offending terminology such as master,slave or whitelist/blacklist as part of [JENKINS-65398](https://issues.jenkins.io/browse/JENKINS-65398)
I tried to update whitelist/ black list with the context, feel free to tell me if it's not accurate.
> [JENKINS-65398] terminology update

- src/main/resources/com/cloudbees/plugins/credentials/Messages_fr.properties
> Correct french typo

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProviderFilter.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsProviderTypeRestriction.java
- src/main/java/com/cloudbees/plugins/credentials/CredentialsTypeFilter.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTypeRestrictionTest.java
- src/test/resources/com/cloudbees/plugins/credentials/CredentialsProviderTypeRestrictionTest/migrateDescriptorClassNameToID/credentials-configuration.xml
https://issues.jenkins.io/browse/JENKINS-67170
https://github.com/jenkinsci/credentials-plugin/pull/235#issuecomment-989899390
> [JENKINS-67170] Complete conversion of `Descriptor.class.name` to `Descriptor.id`

- .github/workflows/cd.yaml
> Forgot to `git add .github/workflows/cd.yaml`

- src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl.java
- src/test/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImplTest.java
> [JENKINS-67132] Default `UsernamePasswordCredentialsImpl.usernameSecret` without `readResolve`

- pom.xml
> Simplify POM

- pom.xml
- src/test/java/com/cloudbees/plugins/credentials/impl/BaseStandardCredentialsTest.java
> Bump parent POM

- pom.xml
> Update Jenkins baseline to 2.319.x

- docs/implementation.adoc
> error: annotated nested classes must be static

- src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/UploadedKeyStoreSource/config.jelly
see https://github.com/jenkinsci/jenkins/pull/7452
(untested but should be fine from what I can see in the PR as most of the inputs didn't have classes before)
> Apply upcoming core styling to file upload

- src/main/resources/lib/credentials/select/select.js
See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I added a new credential from a Freestyle project and verified that the iframe loaded successfully and was refreshed with the new credential after the credential …
> Replace Prototype.js with native JavaScript

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/newDomain.jelly
- src/main/resources/lib/credentials/dialog.js
- src/main/resources/lib/credentials/select/select.js
See https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins/
Manual testing done:
* Created a domain and added credentials to it
* Created a new credential from the "Add" button on a Git SCM configuration page.
```[tasklist]
```
> Prepare for prototype removal

- src/main/java/com/cloudbees/plugins/credentials/SystemCredentialsProvider.java
- src/main/java/com/cloudbees/plugins/credentials/UserCredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTest.java
- src/test/java/com/cloudbees/plugins/credentials/MockFolderCredentialsProvider.java
- src/test/java/com/cloudbees/plugins/credentials/domains/DomainTest.java
- src/test/java/com/cloudbees/plugins/credentials/impl/DummyCredentials.java
Reverts jenkinsci/credentials-plugin#502
> Revert "[JENKINS-72611] Forbid editing credentials ID"

- src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
> Fix Javadoc

- src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/sidepanel.jelly
> Migrate from EE 8 to EE 9 in Jelly view
